blacklist = [
    ('MPUSDT', 'gateio', 'spot'),
    ('ASTEROIDUSDT', 'mexc', 'futures'),
    ('VANRYUSDT', 'gateio', 'spot'),
    ('EWTUSDT', 'mexc', 'spot'),
    ('GTUSDT', 'mexc', 'spot'),
    ('PROSUSDT', 'gateio', 'spot'),
    ('EDGEUSDT', 'gateio', 'all'),
    ('CLSUSDT', 'mexc', 'spot'),
    ('CARRUSDT', 'mexc', 'spot'),
    ('UPUSDT', 'kucoin', 'all'),
    ('EWTUSDT', 'kucoin', 'spot'),
    ('EDGEUSDT', 'bingx', 'spot'),
    ('METAUSDT', 'mexc', 'all'),
    ('SYNUSDT', 'all', 'all'),
    ('FUNUSDT', 'all', 'all'),
    ('CLAWDUSDT', 'htx', 'all'),
    ('GASUSDT', 'mexc', 'all'),
    ('FUNUSDT', 'htx', 'all'),
    ('CVXUSDT', 'htx', 'futures'),
    # ('AIAUSDT', 'all', 'all'),
    # #('PTBUSDT', 'mexc', 'all'),
    # ('LMTSUSDT', 'bingx', 'all'),
    # ('XNLUSDT', 'bingx', 'futures'),
    ('MTLUSDT', 'htx', 'spot'),
    ('BDXUSDT', 'bingx', 'futures'),
    ('REALUSDT', 'gateio', 'spot'),
    ('REALUSDT', 'lbank', 'spot'),
    # ('CARDSUSDT', 'bingx', 'all'),
    # ('XNAPUSDT', 'bingx', 'all'),
    # ('ORACLEUSDT', 'bingx', 'all'),
    # ("MEGAUSDT", "mexc", "all"),
    ("ACNUSDT", "gateio", "spot"),
    # ("HOODUSDT", "lbank", "spot"),
    # ("METAUSDT", "lbank", "spot"),
    # ("XBTUSDT", "lbank", "spot"),
    ("CADUSDT", "gateio", "spot"),
    ("ALLUSDT", "lbank", "spot"),
    ("ALLUSDT", "gateio", "futures"),
    # ("1USDT", "lbank", "spot"),
    ("APPUSDT", "bitget", "futures"),
    ("GMEUSDT", "bitget", "futures"),
    ("GTCUSDT", "gateio", "spot"),
    # ("LIGHTUSDT", "bingx", "spot"),
    # ("LIGHTUSDT", "lbank", "futures"),
    # ("LIGHTUSDT", "lbank", "spot"),
    # ("DREAMSUSDT", "kucoin", "spot"),
    # ("DREAMSUSDT", "mexc", "spot"),
    # ("OPULUSDT", "htx", "futures"),
    # ("CULTUSDT", "gateio", "spot"),
    # ("FLOCKUSDT", "lbank", "spot"),
    ("MAUSDT", "mexc", "spot"),
    ("MAUSDT", "gateio", "spot"),
    # ("YZYUSDT", "lbank", "spot"),
    # ("BLOCKUSDT", "gateio", "spot"),
    # ("BLOCKUSDT", "kucoin", "spot"),
    # ("AINUSDT", "lbank", "spot"),
    ("PEPUSDT", "mexc", "spot"),
    # ("AURAUSDT", "gateio", "spot"),
    # ("AURAUSDT", "mexc", "spot"),
    # ("GARIUSDT", "mexc", "spot"),
    # ("GARIUSDT", "kucoin", "spot"),
    # ("GARIUSDT", "htx", "spot"),
    # ("GARIUSDT", "gateio", "spot"),
    ("ARIAIPUSDT", "bitget", "futures"),
    # ("CVXUSDT", "htx", "futures"),
    ("ARCUSDT", "mexc", "spot"),
    # ("PLUMEUSDT", "htx", "futures"),
    # ("BULLAUSDT", "htx", "all"),
    ("MONUSDT", "htx", "spot"),
    ("MONUSDT", "lbank", "spot"),
    ("BROCCOLIUSDT", "kucoin", "spot"),
    ("ACEUSDT", "kucoin", "spot"),
    ("RIFUSDT", "htx", "spot"),
    ("TRUMPUSDT", "bingx", "spot"),
    # ("DUSKUSDT", "htx", "futures"),
    # ("VICUSDT", "htx", "spot"),
    # ("XMRUSDT", "binance", "spot"),
    ("TSTUSDT", "gateio", "spot"),
    ("TSTUSDT", "kucoin", "spot"),
    # ("SCUSDT", "lbank", "spot"),
    # ("BLDUSDT", "gateio", "spot"),
    # ("MEGAUSDT", "lbank", "spot"),
    ("NUMIUSDT", "gateio", "spot"),    
]